spring.application.name=SecurityManager
server.port=8100

#Spring Cloud Server Config
spring.cloud.config.name=SecurityManager, actuator, security-jwt, logging
spring.config.import=configserver:http://localhost:8099

#Spring Cloud Config SSL Connection
spring.cloud.config.tls.enabled=false
spring.cloud.config.tls.trust-store=classpath:configserver-truststore.p12
spring.cloud.config.tls.trust-store-password=changeit

#SSL
server.ssl.enabled=false
server.ssl.key-store=classpath:securitymanager-keystore.p12
server.ssl.key-store-password=SmPass2026
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=securitymanager

spring.datasource.url=jdbc:h2:file:./src/main/resources/mydb;MODE=Oracle;DATABASE_TO_LOWER=FALSE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Optional web console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console