spring.application.name=SecurityManager
server.port=8100

#Spring Cloud Server Config
spring.cloud.config.name=SecurityManager, actuator
spring.config.import=configserver:http://localhost:8099

#Spring Cloud Config SSL Connection
spring.cloud.config.tls.enabled=false
spring.cloud.config.tls.trust-store=classpath:configserver-truststore.p12
spring.cloud.config.tls.trust-store-password=changeit

#SSL
server.ssl.enabled=false
server.ssl.key-store=classpath:securitymanager-keystore.p12
server.ssl.key-store-password=SmPass2026
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=securitymanager